### ISSUE TITLE
404 from runtime-linked URL

### ISSUE THREAD

**Issue by sigilante** [urbit/operators.urbit.org#59] opened 2022-10-23 19:43 UTC
```
$ ./urbit moon/
~
urbit 1.10
boot: home is /home/neal/moon
boot: mapping 2048MB failed
see urbit.org/using/install/#about-swap-space for adding swap space
if porting to a new platform, try U3_OS_LoomBase 0x7fa6b4f88000
```

This URL 404s for me even after a redirect to operators.urbit.org.

**Comment by matildepark** [comment] 2022-10-31 19:52
Duplicate of https://github.com/urbit/urbit.org/issues/1327 (which also has a paired issue on urbit/urbit)

**Closed by matildepark** 2022-10-31 19:52 UTC
